name: minimal_notes_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.4
  popover: ^0.3.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
